const SEARCH_USERS = 'SEARCH_USERS';
const SET_LOADING = 'SET_LOADING';
const GET_USER = 'GET_USER';
const GET_USER_REPOS = 'GET_USER_REPOS';
const SET_ALERT = 'SET_ALERT';
const REMOVE_ALERT = 'REMOVE_ALERT';

export {
  SEARCH_USERS,
  SET_LOADING,
  GET_USER,
  GET_USER_REPOS,
  SET_ALERT,
  REMOVE_ALERT,
};
